title: "[Node Operator Question] <Title>"
labels: ["node-operator", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        # Node Operator Questions
        
        Before proceeding, please check the discussion section for duplicate questions and check out these links for node operator information:
         - [Node Operator Guide](https://community.optimism.io/docs/developers/bedrock/node-operator-guide/)
         - [Building a Node from Source](https://community.optimism.io/docs/developers/nodes/intro/)
        
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe, in detail, the issue you are having.
    validations:
      required: true

  - type: textarea
    id: node-logs
    attributes:
      label: Node Logs
      description: Please provide relevant logs from the `op-node` and/or `op-geth`.
